
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "mariano",
  "password": "1597"
}

###
GET http://localhost:3000/test-auth   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoibWFyaWFubyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjY3MDUxMTg1LCJleHAiOjE2NjcwNTEyNDV9.3qnZPXx8a8pRYKZUu-z8U5tm1VWKOTEEL8Y1Hc8EtZs

###
GET http://localhost:3000/cliente

### id
GET http://localhost:3000/cliente/1

### numero
GET http://localhost:3000/numero-servico/n/190

### 
POST http://localhost:3000/cliente
Content-Type: application/json

{
  "empresa": "Pedrinho CasaGrande Show",
  "mensalidade": 1799.99,
  "versao": 3.00,
  "dataImplatancao": "2022-04-08",
  "idnum": [135,190],
  "tipo": ["WhatsApp","Hibrido"]
}

### 
POST http://localhost:3000/numero-servico
Content-Type: application/json

{
  "cliente": 4,
  "identificador": 48988270189,
  "ntipo": "Telefone"
}

###
PATCH  http://localhost:3000/numero-servico/13
Content-Type: application/json

{
    "cliente": 4
}

###
PATCH  http://localhost:3000/cliente/1
Content-Type: application/json

{
  "versao": 2.91,
  "observacoes": "Cliente em processo de adição de mais numeros de WhatsApp"
}

###
DELETE http://localhost:3000/cliente/1
